name: tjpcov  # minimum environment for tjpcov development
channels: 
  - conda-forge
  - defaults
dependencies:
  - python=3.6   
  - scipy
  - numpy
  - Jinja2
  - pyyaml
  - pyccl=2.2.0
  - pytest
  - jupyter
